name: Tag Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g., v1.0.0-debug-1)'
        required: true
        type: string
      branch:
        description: 'Branch to tag from (default: current branch)'
        required: false
        type: string
        default: ''

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Create and push tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
          
          echo "Creating tag: $TAG from branch: $BRANCH"
          
          # Create annotated tag
          git tag -a "$TAG" -m "Release $TAG from branch $BRANCH"
          
          # Push the tag
          git push origin "$TAG"
          
          echo "✅ Tag $TAG created successfully from branch $BRANCH"
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Release ${{ github.event.inputs.tag }}
            
            Tagged from branch: ${{ github.event.inputs.branch || github.ref_name }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: ${{ contains(github.event.inputs.tag, '-') }}